Add remove
gilberthappi/To-Do-list pull request #2
Opened 2023-08-22 22:20 UTC by gilberthappi

Use webpack to bundle JavaScript.
Learn how to use proper ES6 syntax.
Use ES6 modules to write modular JavaScript.

2023-08-22 23:58 UTC, Eternalgratis requested changes
# Status: Required Changes ♻️
## Hi @gilberthappi , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!
![almost-there](https://media.giphy.com/media/ReyD4OdRiHeLDCRaEP/giphy.gif)

## Highlights
✅ You used the correct GitHub flow
✅ Descriptive pull request message
✅ Linter error checks validated
✅ Documented your work professionally
✅ Implemented function to add a new task

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-22 23:58 UTC, Eternalgratis commented on src/index.js
>  }
- Kindly create a new file that handles the new functionality to ensure readability
- Please implement the function that edits task description so it enables a user to edit their todo description if they please
- The functionality that deletes tasks and updates the rest of the items and their indexes is missing. Kindly implement this so the user is provided the option to delete tasks

2023-08-23 00:04 UTC, gilberthappi commented on src/index.js
>  }
okey thanks

2023-08-24 22:20 UTC, FrederickMih requested changes
## Hi :raising_hand: :raising_hand: @gilberthappi, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.


<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Nice job for implementing the functions to add and edit a task description :+1: 


## Required Changes ♻️
**N/A**
_Check the comments under the review._

## Optional suggestions
**N/A**

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-24 22:20 UTC, FrederickMih commented on src/index.js
> +refreshUI();
- [ ] Hi @gilberthappi, it is difficult to isolate and debug specific issue when all our codes are in a single file. This is why the previous reviewer asked you to separate the newly added functionalities into a new JavaScript file hence kindly adhered to that specific.

2023-08-24 22:20 UTC, FrederickMih commented on src/index.js
> +});
- [ ] Great job for adding these functionalities as requested by the previous reviewer but unfortunately  I couldn't test and affirm that it is now possible to remove and edit a task description since you didn't add webpack scripts in package.json to bundle your files. Kindly :wrench:  fix this and move a step towards project approval :+1:

2023-08-24 23:56 UTC, Whoistolu commented on src/index.js
> +refreshUI();
- Well resolved

2023-08-24 23:56 UTC, Whoistolu commented on src/index.js
> +});
- Well resolved

2023-08-25 00:06 UTC, Whoistolu approved these changes
### Hi @gilberthappi 

Great job implementing the recommended changes by the previous reviewers 👍🏽 
Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

# STATUS: APPROVED 🟢
**Congratulations! 🎉** 

- [ ]  _Check the inline comments under the review for sections to improve._
- [ ] [OPTIONAL] Kindly add a more detailed description to your PR so that visitors will have an idea of the changes that took place in this milestone.

### Optional suggestions
Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @whoistolu in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-25 00:06 UTC, Whoistolu commented on src/taskUtils.js
> +}
- [ ] [OPTIONAL] It is also a requirement that the property index be set to the value of the new array length (i.e. if a 5th task is added to the list, the index of that task should equal to 5).

Currently, your task indexes start from 0 instead of 1:
<img width="803" alt="Screenshot 2023-08-25 at 00 55 33" src="https://github.com/gilberthappi/To-Do-list/assets/58692590/c33e6653-f0e9-4d7d-9f75-762cdc860c79">

Therefore, to start the index from 1 instead of 0, you can simply add 1 to the index value when creating and updating tasks. 
``` javascript
function Task(description, index) {
  this.description = description;
  this.index = index + 1; 
  this.completed = false;
}
```

2023-08-25 00:11 UTC, merged